server {
    listen 80 default_server;
    server_name _;

    root /var/www/frontend;
    index index.html;

    charset utf-8;

    location /.well-known/acme-challenge/ {
        root /var/www/html/public;
    }

    resolver 127.0.0.11 valid=30s;
    set $upstream app:9000;

    location ^~ /api/ {
        root /var/www/html/public;
        try_files $uri /index.php?$query_string;
    }

    location ^~ /freeswitch/ {
        root /var/www/html/public;
        try_files $uri /index.php?$query_string;
    }

    location ^~ /provision/ {
        root /var/www/html/public;
        try_files $uri /index.php?$query_string;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        root /var/www/html/public;
        fastcgi_pass $upstream;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
